///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestfeb20
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestfeb20Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f327def2-7fb2-4f3f-a561-1c0e1ccd2cdd")]
    public partial class MyTestfeb20Repository : RepoGenBaseFolder
    {
        static MyTestfeb20Repository instance = new MyTestfeb20Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTestfeb20Repository element repository.
        /// </summary>
        [RepositoryFolder("f327def2-7fb2-4f3f-a561-1c0e1ccd2cdd")]
        public static MyTestfeb20Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestfeb20Repository() 
            : base("MyTestfeb20Repository", "/", null, 0, false, "f327def2-7fb2-4f3f-a561-1c0e1ccd2cdd", ".\\RepositoryImages\\MyTestfeb20Repositoryf327def2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f327def2-7fb2-4f3f-a561-1c0e1ccd2cdd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestfeb20RepositoryFolders
    {
    }
#pragma warning restore 0436
}
