///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTestfeb20
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("68cf48a3-3a49-4414-9db3-cd3bccfc05c2", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestfeb20Repository repository.
        /// </summary>
        public static MyTestfeb20Repository repo = MyTestfeb20Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRM.TxtUsername' at 25;0.", repo.OrangeHRM.TxtUsernameInfo, new RecordItemIndex(0));
            repo.OrangeHRM.TxtUsername.Click("25;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Admin' with focus on 'OrangeHRM.TxtUsername'.", repo.OrangeHRM.TxtUsernameInfo, new RecordItemIndex(1));
            repo.OrangeHRM.TxtUsername.PressKeys("Admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'OrangeHRM.TxtUsername'.", repo.OrangeHRM.TxtUsernameInfo, new RecordItemIndex(2));
            repo.OrangeHRM.TxtUsername.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRM.TxtPassword' at 22;6.", repo.OrangeHRM.TxtPasswordInfo, new RecordItemIndex(3));
            repo.OrangeHRM.TxtPassword.Click("22;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin123' with focus on 'OrangeHRM.TxtPassword'.", repo.OrangeHRM.TxtPasswordInfo, new RecordItemIndex(4));
            repo.OrangeHRM.TxtPassword.PressKeys("admin123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRM.BtnLogin' at 20;4.", repo.OrangeHRM.BtnLoginInfo, new RecordItemIndex(5));
            repo.OrangeHRM.BtnLogin.Click("20;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://opensource-demo.orangehrmlive.com/webres_5df488ddad8b23.30204013/themes/default/images/logo.png') on item 'OrangeHRM.OrangeHRM'.", repo.OrangeHRM.OrangeHRMInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.OrangeHRM.OrangeHRMInfo, "Src", "https://opensource-demo.orangehrmlive.com/webres_5df488ddad8b23.30204013/themes/default/images/logo.png");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
